import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import SiteHeader from '@/components/site-header'


const poppins = Poppins({ weight: ['400', '600', '700'], subsets: ['latin'], })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className + " bg-blue-500"}>
        <SiteHeader />
        {children}
        </body>
    </html>
  )
}
